title: "AAN, het Anti Abuse Netwerk"
author: "AAN, het Anti Abuse Netwerk"
email: info@abuse.nl
description: > # this means to ignore newlines until "baseurl:"
  Coalitie voor een schoner en veiliger internet door een effective aanpak van internet veiligheids problemen.

twitter_username: macrod68
github_username:  macrod68

sass:
    style: compressed

collections:
  deelnemers:
    output: true