version: 2
jobs:

  build:
    docker:
      - image: mrseccubus/github-pages:latest
    steps:
#      - run: apt-get update && apt-get install -y ssh git
      - (cd /root/;rm -rf project;mkdir project)
      - checkout
      - run:
          name: Build site
          command: |
            jekyll build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build