version: 2
jobs:

  build:
    docker:
      - image: mrseccubus/github-pages:latest
    steps:
#      - run: apt-get update && apt-get install -y ssh git
      - run: (cd /root/;rm -rf project;mkdir project)
      - checkout
      - run:
          name: Build site
          command: |
            jekyll build
      - store_artifacts:
          path: /root/project/_site/
      - save_cache:
          key: jekyll-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - "/root/project/_site"


  upload:
    docker:
      - image: alpine:latest
    steps:
      - restore_cache:
          key: jekyll-{{ .Environment.CIRCLE_SHA1 }}
      - run: ls -al /root/project/_site



workflows:
  version: 2
  build_and_upload:
    jobs:
      - build
      - upload:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - circleci-test
